services:
  mysql_db:
    image: mysql:8.0
    container_name: proiectis2_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword123@
      MYSQL_DATABASE: proiectis2_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: parolaIS2API123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./ProiectIS2/Dockerfile
      args:
        DB_USER: testuser
        DB_PASSWORD: parolaIS2API123
        DB_HOST: mysql_db
        DB_DATABASE: proiectis2_db
    container_name: proiectis2_app
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      DB_USER: testuser
      DB_PASSWORD: parolaIS2API123
      DB_HOST: mysql_db
      DB_DATABASE: proiectis2_db
      USE_MIDDLEWARE: "no"
      SEED_DATABASE: "no"
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      mysql_db:
        condition: service_healthy
    restart: on-failure

volumes:
  db_data:
    driver: local